#!/usr/bin/env python3
# P9 part 3: can the Qt side of the notice job be generated offline from what
# aqt installed? Builds a THIRD-PARTY-NOTICES draft from the module SBOMs and
# measures which license FULL TEXTS are still missing locally.
import os
import re
import json
import collections

QT = r"C:/Users/baiyl3/dev/qt/6.10.1/msvc2022_64"
SBOM = os.path.join(QT, "sbom")
HERE = os.path.dirname(os.path.abspath(__file__))
EV = os.path.join(HERE, "evidence")
OUT = os.path.join(HERE, "out")
os.makedirs(OUT, exist_ok=True)

# DLL families actually shipped in the pinned package, mapped to their SBOM module.
SHIPPED_MODULES = ["qtbase", "qtdeclarative", "qtsvg", "qtimageformats"]
BUILD_MODULES = ["qtshadertools", "qttools", "qttranslations"]

SPLIT = re.compile(r"\s+(?:AND|OR|WITH)\s+", re.I)


def tokens(expr):
    expr = expr.strip().strip("()")
    parts = SPLIT.split(expr)
    out = []
    for p in parts:
        p = p.strip(" ()")
        if p and p.upper() not in ("AND", "OR", "WITH"):
            out.append(p)
    return out


docs = {}
for fn in sorted(os.listdir(SBOM)):
    if fn.endswith(".spdx.json"):
        docs[fn.split("-6.10.1")[0]] = json.load(open(os.path.join(SBOM, fn), encoding="utf-8"))

lines = []
lines.append("# Third-party notices (generated draft, spike P9)")
lines.append("")
lines.append("Generated by `spike/p9-licenses/gen_notices.py` from the SPDX SBOMs that")
lines.append("aqt installed under `%s`." % SBOM)
lines.append("")

all_ids = collections.Counter()
pkg_total = 0
for mod, j in sorted(docs.items()):
    tag = "shipped" if mod in SHIPPED_MODULES else ("build-time" if mod in BUILD_MODULES else "?")
    pgs = j.get("packages", [])
    lines.append("## %s (6.10.1) — %d package records [%s]" % (mod, len(pgs), tag))
    infos = {e.get("licenseId"): e for e in j.get("hasExtractedLicensingInfos", [])}
    for pg in sorted(pgs, key=lambda p: p.get("name", "")):
        nm = pg.get("name", "")
        lic = str(pg.get("licenseConcluded"))
        cr = str(pg.get("copyrightText", "")).replace("\n", " / ")
        lines.append("- **%s** %s — `%s`" % (nm, pg.get("versionInfo") or "", lic))
        lines.append("  - copyright: %s" % (cr[:300] or "(none)"))
        for t in tokens(lic):
            if t.startswith("LicenseRef-"):
                e = infos.get(t)
                txt = (e or {}).get("extractedText", "")
                lines.append("  - LicenseRef text (%d chars): %s" % (
                    len(txt), " ".join(str(txt).split())[:400]))
            all_ids[t] += 1
        pkg_total += 1
    lines.append("")

with open(os.path.join(OUT, "THIRD-PARTY-NOTICES.md"), "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(lines) + "\n")

# Which license ids would need a full text shipped, and do we have one locally?
std = {t for t in all_ids if not t.startswith("LicenseRef-")}
search_roots = [
    ("qt-install", QT),
    ("rust-license-texts", os.path.join(HERE, "licenses")),
    ("windows-kits", r"C:/Program Files (x86)/Windows Kits/10/Licenses"),
]
NAME_RE = re.compile(r"licen[cs]e|copying|copyright|unlicense|eula", re.I)
SHORT = {"gpl", "lgpl", "agpl", "mpl", "mit", "bsd", "ofl", "zlib", "apache", "isc",
         "unicode", "cc0", "bsl", "libpng", "libtiff", "ftl", "ijg", "hpnd", "x11",
         "bison", "aml", "khronos", "imlib2", "glslang", "sljit"}


def lic_named_files():
    """Every file whose *name* is license-like, across the three local roots."""
    idx = []
    for tag, root in search_roots:
        if not os.path.isdir(root):
            continue
        for dp, dns, fs in os.walk(root):
            for f in fs:
                stem = os.path.splitext(f)[0].lower()
                toks = [t for t in re.split(r"[^a-z0-9]+", stem) if t]
                if NAME_RE.search(f) or (set(toks) & SHORT):
                    idx.append((tag, os.path.join(dp, f).replace(root, "").lstrip("\/")))
    return idx


def has_text(idx, sid):
    toks = [t for t in re.split(r"[^a-z0-9]+", sid.lower()) if t and len(t) > 1]
    hits = []
    for tag, rel in idx:
        ftoks = [t for t in re.split(r"[^a-z0-9]+", rel.lower()) if t]
        if all(any(t in ft for ft in ftoks) for t in toks[:3]):
            hits.append("%s:%s" % (tag, rel))
    return hits


idx = lic_named_files()
report = []
report.append("=== license-named files available locally: %d ===" % len(idx))
for tag in ("qt-install", "rust-license-texts", "windows-kits"):
    report.append("  %-22s %d" % (tag, sum(1 for t, _ in idx if t == tag)))
report.append("")
report.append("=== distinct license id tokens across the 7 SBOMs ===")
for k, v in all_ids.most_common():
    report.append("  %5d  %s" % (v, k))
report.append("")
report.append("package records total: %d ; distinct license id tokens: %d (LicenseRef: %d, SPDX std: %d)" % (
    pkg_total, len(all_ids), len(all_ids) - len(std), len(std)))
report.append("")
report.append("=== is a license TEXT for this id present locally? (matched against license-named files only) ===")
missing = []
for sid in sorted(std):
    h = has_text(idx, sid)
    report.append("  %-50s %s" % (sid, h[0] if h else "NO LOCAL TEXT"))
    if not h:
        missing.append(sid)
report.append("")
report.append("ids with no local text: %d" % len(missing))
for m in missing:
    report.append("  " + m)

with open(os.path.join(EV, "spdx-coverage.txt"), "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(report) + "\n")
print("\n".join(report[-(len(missing) + 4):]))
print("notices draft lines: %d ; package records: %d" % (len(lines), pkg_total))
